package com.agrelius.wasegmul.network

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Pure unit tests for GTIN helpers (audit §3.58). Check digits verified by hand
 * against the GS1 Modulo-10 algorithm — never generated by the impl under test.
 */
class GtinValidationTest {

    @Test
    fun validGtins_accepted() {
        assertTrue(OpenFoodFactsApi.isValidGtin("3017620422003")) // Nutella EAN-13
        assertTrue(OpenFoodFactsApi.isValidGtin("96385074")) // EAN-8
        assertTrue(OpenFoodFactsApi.isValidGtin("036000291452")) // UPC-A
        assertTrue(OpenFoodFactsApi.isValidGtin("13017620422000")) // GTIN-14
        assertTrue(OpenFoodFactsApi.isValidGtin(" 3017620422003 ")) // surrounding spaces
        assertTrue(OpenFoodFactsApi.isValidGtin("3017620422-003")) // dashes stripped
    }

    @Test
    fun invalidGtins_rejected() {
        assertFalse(OpenFoodFactsApi.isValidGtin(null))
        assertFalse(OpenFoodFactsApi.isValidGtin(""))
        assertFalse(OpenFoodFactsApi.isValidGtin("   "))
        assertFalse(OpenFoodFactsApi.isValidGtin("123")) // bad length
        assertFalse(OpenFoodFactsApi.isValidGtin("3017620422004")) // bad check digit
        assertFalse(OpenFoodFactsApi.isValidGtin("036000291453")) // bad check digit
        assertFalse(OpenFoodFactsApi.isValidGtin("https://example.com/x")) // scanner junk
        assertFalse(OpenFoodFactsApi.isValidGtin("301762042200A")) // letters
        // All-zero passes the Modulo-10 checksum (GS1-reserved range, but structurally valid):
        // checksum validation answers "well-formed", not "allocated".
        assertTrue(OpenFoodFactsApi.isValidGtin("0000000000000"))
    }

    @Test
    fun normaliseGtin_stripsToDigits() {
        assertEquals("3017620422003", OpenFoodFactsApi.normaliseGtin(" 3017620422-003 "))
        assertNull(OpenFoodFactsApi.normaliseGtin(null))
        assertNull(OpenFoodFactsApi.normaliseGtin("---"))
    }
}
